print("#########", sep='\n')
print('#','#', sep='\t')
print('#','#', sep='\t')
print('#','#', sep='\t')
print('#########', end='\n\n')
# letters H
print('#','#', sep='\t')
print('#','#', sep='\t')
print('#########', sep='\n')
print('#','#', sep='\t')
print('#','#', sep='\t')